chore: reduce time of rebuilding across workspace
Signed-off-by: Alex Chi <iskyzh@gmail.com>

diff --git a/Makefile.toml b/Makefile.toml
--- a/Makefile.toml
+++ b/Makefile.toml
@@ -269,14 +269,10 @@ command = "scripts/source/prepare_source.sh"
 
 
 [tasks.ci-v2]
-category = "RiseDev - Start"
-dependencies = [
-  "pre-start-playground"
-]
-command = "rust/target/${BUILD_MODE_DIR}/risedev-playground"
-args = ["ci-v2"]
-description = "Start a RisingWave playground ci-v2 config"
-
+script = """
+echo \"directly calling ./risedev ci-v2 has been deprecated. Use ./risedev dev ci-v2 instead.\"
+exit 1
+"""
 
 [tasks.ci-3node]
 script = """
@@ -309,37 +305,74 @@ echo \"directly calling ./risedev dev-meta-node has been deprecated. Use ./rised
 exit 1
 """
 
-[tasks.install-sqllogictest]
+[tasks.install-tools]
+category = "RiseDev - Check"
 script = """
 #!/bin/bash
 set -e
+cargo install cargo-llvm-cov cargo-nextest cargo-udeps cargo-hakari cargo-sort
 cargo install --git https://github.com/risinglightdb/sqllogictest-rs --features bin
 """
+description = "Install required tools to do pre-CI check and run e2e tests"
 
-[tasks.install-llvm-cov]
-script = """
-#!/bin/bash
-set -e
-cargo install cargo-llvm-cov --git https://github.com/skyzh/cargo-llvm-cov --rev 180e62
-"""
-
-[tasks.install-nextest]
-script = """
-#!/bin/bash
-set -e
-cargo install cargo-nextest
-"""
-
-[tasks.test-coverage]
+[tasks.test-cov]
+category = "RiseDev - Check"
 script = """
 #!/bin/bash
 set -e
 
 cd rust
-CARGO_TARGET_DIR=target/coverage
-cargo llvm-cov nextest
+export CARGO_TARGET_DIR=target/coverage
+cargo llvm-cov nextest --html
 """
+description = "Run unit tests and report coverage"
+
+[tasks.test]
+category = "RiseDev - Check"
+script = """
+#!/bin/bash
+set -e
+
+echo "If any command is not found, run $(tput setaf 4)./risedev install-tools$(tput sgr0) to install required tools."
+
+cd rust
+cargo nextest run
+"""
+description = "Run unit tests"
+
+[tasks.check]
+category = "RiseDev - Check"
+script = """
+#!/bin/bash
+
+cd rust
+
+echo "If any command is not found, run $(tput setaf 4)./risedev install-tools$(tput sgr0) to install required tools."
+
+echo "Running $(tput setaf 4)cargo hakari$(tput sgr0) checks"
+cargo hakari generate
+test $? -eq 0 || exit 1
+
+echo "Running $(tput setaf 4)cargo sort$(tput sgr0) checks"
+# We only check instead of format here beacuse everytime cargo sort rewrites all files, the crates will be rebuilt.
+# Therefore, users shoud run cargo sort themselves when new deps are added.
+cargo sort -w -c
+test $? -eq 0 || { echo "cargo sort check failed. You may run $(tput setaf 4)cargo sort -w$(tput sgr0) to fix it."; exit 1; }
+
+echo "Running $(tput setaf 4)cargo fmt$(tput sgr0) checks"
+cargo fmt --all
+test $? -eq 0 || exit 1
+
+echo "Running $(tput setaf 4)cargo clippy$(tput sgr0) checks"
+cargo clippy --workspace --all-targets
+echo "If cargo clippy check failed or generates warning. You may run $(tput setaf 4)cargo clippy --workspace --all-targets --fix$(tput sgr0) to fix it. Note that clippy fix requires manual review, as not all auto fixes are guaranteed to be reasonable."
+
+echo
+echo "Done! You may run $(tput setaf 4)./risedev test$(tput sgr0) or $(tput setaf 4)./risedev test-cov$(tput sgr0) to run unit tests."
+"""
+description = "Perform pre-CI checks and automatically fix cargo sort, cargo hakari, cargo fmt warnings"
 
 [tasks.apply-ci-template]
-description = "Apply CI template"
+category = "RiseDev - Check"
 command = ".github/workflow-template/generate.sh"
+description = "Update CI workflow by applying templates"
