update madsim to v0.2.0-alpha.6 and tonic to v0.8
now additional system protoc is required.

Signed-off-by: Runji Wang <wangrunji0408@163.com>

diff --git a/Makefile.toml b/Makefile.toml
--- a/Makefile.toml
+++ b/Makefile.toml
@@ -398,6 +398,10 @@ echo
 echo "check: $(tput setaf 4)cmake$(tput sgr0)"
 cmake --version || echo "$(tput setaf 3)cmake$(tput sgr0) not found."
 echo
+
+echo "check: $(tput setaf 4)protoc$(tput sgr0)"
+protoc --version || echo "$(tput setaf 3)protoc$(tput sgr0) not found."
+echo
 """
 description = "Install required tools to do pre-CI check and run e2e tests"
 
