feat(risedev): support docker image for `USE_SYSTEM_RISINGWAVE` (#21520)
Signed-off-by: Bugen Zhao <i@bugenzhao.com>

diff --git a/Makefile.toml b/Makefile.toml
--- a/Makefile.toml
+++ b/Makefile.toml
@@ -369,14 +369,18 @@ script = '''
 
 set -e
 
-rw_path=$(command -v risingwave || true)
-if [[ -z "${rw_path}" ]]; then
-  echo "$(tput setaf 1)$(tput bold)[ERROR]$(tput sgr0) env $(tput setaf 5)USE_SYSTEM_RISINGWAVE$(tput sgr0) is set, but $(tput setaf 5)risingwave$(tput sgr0) is not found in PATH."
-  exit 1
+if [[ "${USE_SYSTEM_RISINGWAVE}" == docker:* ]]; then
+  tag="${USE_SYSTEM_RISINGWAVE#docker:}"
+  echo "$(tput setaf 5)$(tput bold)[Info]$(tput sgr0) env $(tput setaf 5)USE_SYSTEM_RISINGWAVE$(tput sgr0) is set, will use docker image $(tput setaf 5)risingwavelabs/risingwave:${tag}$(tput sgr0)."
+else
+  rw_path=$(command -v risingwave || true)
+  if [[ -z "${rw_path}" ]]; then
+    echo "$(tput setaf 1)$(tput bold)[ERROR]$(tput sgr0) env $(tput setaf 5)USE_SYSTEM_RISINGWAVE$(tput sgr0) is set, but $(tput setaf 5)risingwave$(tput sgr0) is not found in PATH."
+    exit 1
+  fi
+  version=$(risingwave --version)
+  echo "$(tput setaf 5)$(tput bold)[Info]$(tput sgr0) env $(tput setaf 5)USE_SYSTEM_RISINGWAVE$(tput sgr0) is set, will use $(tput setaf 5)$version$(tput sgr0) found at $rw_path."
 fi
-
-version=$(risingwave --version)
-echo "$(tput setaf 5)$(tput bold)[Info]$(tput sgr0) env $(tput setaf 5)USE_SYSTEM_RISINGWAVE$(tput sgr0) is set, will use $(tput setaf 5)$version$(tput sgr0) found at $rw_path."
 '''
 
 [tasks.b]
