feat(test): make simulation test deterministic! (#4336)
* 3 compute nodes

Signed-off-by: Runji Wang <wangrunji0408@163.com>

* revert `madsim::time::Instant` to std's

Signed-off-by: Runji Wang <wangrunji0408@163.com>

* make `RowIdGenerator` async

Signed-off-by: Runji Wang <wangrunji0408@163.com>

* switch to nextest

Signed-off-by: Runji Wang <wangrunji0408@163.com>

* fix simulated e2e test

Signed-off-by: Runji Wang <wangrunji0408@163.com>

* update madsim to v0.2.0-alpha.6 and tonic to v0.8

now additional system protoc is required.

Signed-off-by: Runji Wang <wangrunji0408@163.com>

Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>

diff --git a/Makefile.toml b/Makefile.toml
--- a/Makefile.toml
+++ b/Makefile.toml
@@ -398,6 +398,10 @@ echo
 echo "check: $(tput setaf 4)cmake$(tput sgr0)"
 cmake --version || echo "$(tput setaf 3)cmake$(tput sgr0) not found."
 echo
+
+echo "check: $(tput setaf 4)protoc$(tput sgr0)"
+protoc --version || echo "$(tput setaf 3)protoc$(tput sgr0) not found."
+echo
 """
 description = "Install required tools to do pre-CI check and run e2e tests"
 
@@ -434,7 +438,7 @@ description = "Run unit tests"
 category = "RiseDev - Build in simulation mode"
 description = "Build in simulation mode"
 dependencies = ["warn-on-missing-tools"]
-env = { RUSTFLAGS = "--cfg tokio_unstable --cfg madsim", CARGO_TARGET_DIR = "target/sim" }
+env = { RUSTFLAGS = "--cfg tokio_unstable --cfg madsim", RUSTDOCFLAGS = "--cfg madsim", CARGO_TARGET_DIR = "target/sim" }
 script = """
 #!/bin/bash
 set -e
@@ -446,12 +450,12 @@ cargo build "$@"
 category = "RiseDev - Deterministic Simulation Test"
 description = "Run unit tests in deterministic simulation mode"
 dependencies = ["warn-on-missing-tools"]
-env = { RUSTFLAGS = "--cfg tokio_unstable --cfg madsim", CARGO_TARGET_DIR = "target/sim" }
+env = { RUSTFLAGS = "--cfg tokio_unstable --cfg madsim", RUSTDOCFLAGS = "--cfg madsim", CARGO_TARGET_DIR = "target/sim" }
 script = """
 #!/bin/bash
 set -e
 
-cargo test "$@"
+cargo nextest run "$@"
 """
 
 [tasks.check-hakari]
