error when use USE_SYSTEM_RISINGWAVE for risedev ctl

diff --git a/Makefile.toml b/Makefile.toml
--- a/Makefile.toml
+++ b/Makefile.toml
@@ -722,6 +722,11 @@ dependencies = [
 ]
 script = '''
 #!/usr/bin/env bash
+if [[ -n "${USE_SYSTEM_RISINGWAVE}" ]]; then
+  echo "$(tput setaf 1)$(tput bold)[ERROR]$(tput sgr0) env $(tput setaf 5)USE_SYSTEM_RISINGWAVE$(tput sgr0) is set, but $(tput setaf 5)./risedev ctl$(tput sgr0) is not supported in this mode yet."
+  exit 1
+fi
+
 "${PREFIX_BIN}/risingwave/risectl" "$@"
 test $? -eq 0 || exit 1
 '''
