add jdbc test, change ci workflow

diff --git a/.github/workflows/connector-node-integration.yml b/.github/workflows/connector-node-integration.yml
--- a/.github/workflows/connector-node-integration.yml
+++ b/.github/workflows/connector-node-integration.yml
@@ -76,15 +76,27 @@ jobs:
           pip3 install grpcio grpcio-tools psycopg2 psycopg2-binary pyspark==3.3
           cd python-client && bash gen-stub.sh
 
+          echo "--- generate integration tests stream chunk data"
+          cargo run --bin data-chunk-payload-convert-generator data/sink_input_new.json > ./data/sink_input
+          cargo run --bin data-chunk-payload-generator unit-test > ./data/stream_chunk_data
+
+          echo "--- running streamchunk integration tests"
+          if python integration_tests.py --stream_chunk_sink --input_binary_file ./data/stream_chunk_data; then
+            echo "Streamchunk sink test passed"
+          else
+            echo "Streamchunk sink test failed"
+            exit 1
+          fi
+
           echo "--- running jdbc integration tests"
-          if python3 integration_tests.py --file_sink; then
+          if python3 integration_tests.py --file_sink --input_binary_file ./data/sink_input; then
             echo "File sink test passed"
           else
             echo "File sink test failed"
             exit 1
           fi
 
-          if python3 integration_tests.py --jdbc_sink; then
+          if python3 integration_tests.py --jdbc_sink --input_binary_file ./data/sink_input; then
             echo "Jdbc sink test passed"
           else
             echo "Jdbc sink test failed"
