fmt toml

diff --git a/.github/workflows/connector-node-integration.yml b/.github/workflows/connector-node-integration.yml
--- a/.github/workflows/connector-node-integration.yml
+++ b/.github/workflows/connector-node-integration.yml
@@ -80,19 +80,19 @@ jobs:
           # cargo run --bin data-chunk-payload-convert-generator data/sink_input_new.json > ./data/sink_input
           # cargo run --bin data-chunk-payload-generator unit-test > ./data/stream_chunk_data
 
-          echo "--- running streamchunk integration tests"
-          if python integration_tests.py --stream_chunk_sink --input_binary_file ./data/stream_chunk_data; then
-            echo "Streamchunk sink test passed"
-          else
-            echo "Streamchunk sink test failed"
-            exit 1
-          fi
-
           echo "--- running jdbc integration tests"
           if python3 integration_tests.py --file_sink --input_binary_file ./data/sink_input; then
             echo "File sink test passed"
           else
             echo "File sink test failed"
+            exit 1
+          fi
+
+          echo "--- running streamchunk integration tests"
+          if python integration_tests.py --stream_chunk_sink --input_binary_file ./data/stream_chunk_data; then
+            echo "Streamchunk sink test passed"
+          else
+            echo "Streamchunk sink test failed"
             exit 1
           fi
 
